create table
  public.global_user_roles (
    id bigint generated by default as identity,
    name text null,
    created_at timestamp with time zone not null default now(),
    constraint global_user_role_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.global_users (
    id bigint generated by default as identity,
    first_name text null,
    last_name text null,
    phone text null,
    email text null,
    username text null,
    password text null,
    is_root boolean null default false,
    user_role_id bigint null,
    created_at timestamp with time zone not null default now(),
    is_active boolean null default false,
    token text null,
    constraint global_users_pkey primary key (id),
    constraint global_users_user_role_id_fkey foreign key (user_role_id) references global_user_roles (id) on update cascade on delete set default
  ) tablespace pg_default;