-- Drop tables if they exist
DROP TABLE IF EXISTS public.currency_types CASCADE;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.countries CASCADE;
DROP TABLE IF EXISTS public.platform_user_genders CASCADE;
DROP TABLE IF EXISTS public.course_levels CASCADE;
DROP TABLE IF EXISTS public.student_course_enrollment_final_exam_attempt_tries CASCADE;
DROP TABLE IF EXISTS public.student_course_enrollment_final_exam_attempts CASCADE;
DROP TABLE IF EXISTS public.student_course_enrollments CASCADE;
DROP TABLE IF EXISTS public.platform_users CASCADE;
DROP TABLE IF EXISTS public.platform_user_roles CASCADE;
DROP TABLE IF EXISTS public.course_module_classes CASCADE;
DROP TABLE IF EXISTS public.course_platform_tools CASCADE;
DROP TABLE IF EXISTS public.course_modules CASCADE;
DROP TABLE IF EXISTS public.course_final_exam_option_answers CASCADE;
DROP TABLE IF EXISTS public.course_final_exam_questions CASCADE;
DROP TABLE IF EXISTS public.course_final_exams CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;
DROP TABLE IF EXISTS public.course_formats CASCADE;
DROP TABLE IF EXISTS public.platform_states CASCADE;

-- Create tables
CREATE TABLE public.currency_types (
    id SERIAL PRIMARY KEY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    UNIQUE (abbreviation),
    created_at TIMESTAMP with time zone NOT NULL default now()
);

CREATE TABLE public.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    constraint payment_methods_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

CREATE TABLE public.countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_user_genders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT platform_user_genders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_user_role_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NULL,
    last_name TEXT NULL,
    phone TEXT NULL,
    email TEXT NULL,
    username TEXT NULL,
    password TEXT NULL,
    is_root BOOLEAN NULL default false,
    user_role_id BIGINT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    is_active BOOLEAN NULL default false,
    token TEXT NULL,
    dni_ssn TEXT NULL,
    platform_user_gender_id BIGINT NULL default '4'::BIGINT,
    country_id BIGINT NULL,
    CONSTRAINT platform_users_pkey PRIMARY KEY (id),
    CONSTRAINT platform_users_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_platform_user_gender_id_fkey FOREIGN KEY (platform_user_gender_id) REFERENCES platform_user_genders (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES platform_user_roles (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE public.platform_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_states_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.course_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT course_level_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

CREATE TABLE public.courses (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    has_final_exam BOOLEAN NULL DEFAULT true,
    is_paid BOOLEAN NULL DEFAULT true,
    course_level_id BIGINT NULL,
    description TEXT NULL,
    payment_methods JSONB NULL,
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT courses_course_level_id_fkey FOREIGN KEY (course_level_id) REFERENCES course_levels (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE public.course_final_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    course_id BIGINT NULL,
    title TEXT NULL,
    description TEXT NULL,
    min_score_to_pass DOUBLE PRECISION NULL,
    questions_associated NUMERIC NULL DEFAULT '0'::NUMERIC,
    CONSTRAINT course_final_exams_pkey PRIMARY KEY (id),
    CONSTRAINT course_final_exams_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.course_final_exam_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_final_exam_id BIGINT NULL,
    question_text TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    points_assigned DOUBLE PRECISION NULL DEFAULT '1'::DOUBLE PRECISION,
    CONSTRAINT course_final_exam_questions_pkey PRIMARY KEY (id),
    CONSTRAINT course_final_exam_questions_course_final_exam_id_fkey FOREIGN KEY (course_final_exam_id) REFERENCES course_final_exams (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.course_final_exam_option_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_final_exam_question_id BIGINT NULL,
    answer_text TEXT NULL,
    is_correct BOOLEAN NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT course_final_exam_option_answers_pkey PRIMARY KEY (id),
    CONSTRAINT course_final_exam_option_answ_course_final_exam_question_i_fkey FOREIGN KEY (course_final_exam_question_id) REFERENCES course_final_exam_questions (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.course_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NULL,
    title TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT course_modules_pkey PRIMARY KEY (id),
    CONSTRAINT course_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.course_formats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT course_formats_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.course_platform_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    link TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT course_platform_tools_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.course_module_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_module_id BIGINT NULL,
    title TEXT NULL,
    course_format_id BIGINT NULL,
    description TEXT NULL,
    video_link TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    course_platform_tool_id BIGINT NULL,
    has_video BOOLEAN NULL DEFAULT FALSE,
    has_link_to_drive BOOLEAN NULL DEFAULT FALSE,
    drive_link TEXT NULL,
    time_to_complete BIGINT NULL,
    CONSTRAINT course_module_classes_pkey PRIMARY KEY (id),
    CONSTRAINT course_module_classes_course_format_id_fkey FOREIGN KEY (course_format_id) REFERENCES course_formats (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT course_module_classes_course_module_id_fkey FOREIGN KEY (course_module_id) REFERENCES course_modules (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT course_module_classes_course_platform_tool_id_fkey FOREIGN KEY (course_platform_tool_id) REFERENCES course_platform_tools (id)
) TABLESPACE pg_default;

CREATE TABLE public.student_course_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    enrollment_date DATE NULL,
    platform_user_id BIGINT NULL,
    course_id BIGINT NULL,
    currency_abbreviation TEXT NULL DEFAULT 'No aplica'::TEXT,
    payment DOUBLE PRECISION NULL,
    platform_state_id BIGINT NULL DEFAULT '1'::BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT student_course_enrollment_pkey PRIMARY KEY (id),
    CONSTRAINT student_course_enrollment_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT student_course_enrollments_platform_state_id_fkey FOREIGN KEY (platform_state_id) REFERENCES platform_states (id) ON UPDATE CASCADE ON DELETE SET DEFAULT,
    CONSTRAINT student_course_enrollments_platform_user_id_fkey FOREIGN KEY (platform_user_id) REFERENCES platform_users (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.student_course_enrollment_final_exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    total_attempts BIGINT NULL,
    best_score DOUBLE PRECISION NULL,
    student_course_enrollment_id BIGINT NULL,
    is_lock BOOLEAN NOT NULL DEFAULT FALSE,
    lock_expiration_date DATE NULL,
    is_approved BOOLEAN NULL DEFAULT FALSE,
    attempts_count_period BIGINT NULL DEFAULT '0'::BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT student_course_enrollment_final_exam_attempts_pkey PRIMARY KEY (id),
    CONSTRAINT student_course_enrollment_fin_student_course_enrollment_id_fkey FOREIGN KEY (student_course_enrollment_id) REFERENCES student_course_enrollments (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.student_course_enrollment_final_exam_attempt_tries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date DATE NULL DEFAULT NOW(),
    student_course_enrollment_final_exam_attempt_id BIGINT NULL,
    score DOUBLE PRECISION NULL,
    answers JSON NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT student_course_enrollment_final_exam_attempt_single_pkey PRIMARY KEY (id),
    CONSTRAINT student_course_enrollment_fin_student_course_enrollment_fi_fkey FOREIGN KEY (student_course_enrollment_final_exam_attempt_id) REFERENCES student_course_enrollment_final_exam_attempts (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;
