-- Drop tables if they exist
DROP TABLE IF EXISTS public.currency_types CASCADE;
DROP TABLE IF EXISTS public.product_categories CASCADE;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.countries CASCADE;
DROP TABLE IF EXISTS public.platform_user_genders CASCADE;
DROP TABLE IF EXISTS public.platform_users CASCADE;
DROP TABLE IF EXISTS public.platform_user_roles CASCADE;
DROP TABLE IF EXISTS public.platform_states CASCADE;
DROP TABLE IF EXISTS public.platform_settings CASCADE;

-- Create tables
CREATE TABLE public.product_categories (
    id BIGINT generated by default AS identity,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT product_categories_name_key unique (name)
  ) TABLESPACE pg_default;

CREATE TABLE public.product_measure_units (
    id BIGINT generated by default AS identity,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT product_measure_units_pkey PRIMARY KEY (id),
    CONSTRAINT product_measure_units_name_key unique (name)
  ) TABLESPACE pg_default;

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(100) NOT NULL,
    description TEXT,  
    image_path TEXT,               
    product_category_id INTEGER NOT NULL REFERENCES product_categories(id), 
    price DECIMAL(10, 2) NOT NULL,       
    product_measure_unit_id INTEGER NOT NULL REFERENCES product_measure_units(id),     
    quantity INTEGER NOT NULL,                 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.currency_types (
    id SERIAL PRIMARY KEY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    UNIQUE (abbreviation),
    created_at TIMESTAMP with time zone NOT NULL default now()
);

CREATE TABLE public.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

CREATE TABLE public.countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_user_genders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT platform_user_genders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_settings (
    id BIGINT generated by default AS identity,
    contact_number VARCHAR(15) NULL,
    developer_name VARCHAR(100) NOT NULL,
    developer_contact_email VARCHAR(100) NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT platform_settings_pkey PRIMARY KEY (id),
    CONSTRAINT platform_settings_name_key UNIQUE (developer_name)
) TABLESPACE pg_default;

CREATE TABLE public.platform_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_user_role_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NULL,
    last_name TEXT NULL,
    phone TEXT NULL,
    email TEXT NULL,
    username TEXT NULL,
    password TEXT NULL,
    is_root BOOLEAN NULL default false,
    user_role_id BIGINT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    is_active BOOLEAN NULL default false,
    token TEXT NULL,
    dni_ssn TEXT NULL,
    platform_user_gender_id BIGINT NULL default '4'::BIGINT,
    country_id BIGINT NULL,
    CONSTRAINT platform_users_pkey PRIMARY KEY (id),
    CONSTRAINT platform_users_email_key unique (email),
    CONSTRAINT platform_users_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_platform_user_gender_id_fkey FOREIGN KEY (platform_user_gender_id) REFERENCES platform_user_genders (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES platform_user_roles (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE public.platform_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_states_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
