-- Drop tables if they exist
DROP TABLE IF EXISTS public.currency_types CASCADE;
DROP TABLE IF EXISTS public.stock_products;
DROP TABLE IF EXISTS public.product_categories CASCADE;
DROP TABLE IF EXISTS public.product_measure_units;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.countries CASCADE;
DROP TABLE IF EXISTS public.platform_user_genders CASCADE;
DROP TABLE IF EXISTS public.platform_users CASCADE;
DROP TABLE IF EXISTS public.platform_user_roles CASCADE;
DROP TABLE IF EXISTS public.platform_states CASCADE;
DROP TABLE IF EXISTS public.platform_settings CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.sale_items CASCADE;

-- Create tables
CREATE TABLE public.product_categories (
    id BIGINT generated by default AS identity,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT product_categories_name_key unique (name)
  ) TABLESPACE pg_default;

CREATE TABLE public.product_measure_units (
    id BIGINT generated by default AS identity,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT product_measure_units_pkey PRIMARY KEY (id),
    CONSTRAINT product_measure_units_name_key unique (name)
  ) TABLESPACE pg_default;

create table public.stock_products (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  description text null,
  has_image boolean not null default false,
  image_path text null,
  product_category_id integer not null,
  price numeric(10, 2) not null,
  product_measure_unit_id integer not null,
  quantity integer not null,
  has_bar_code boolean not null default false,
  bar_code text null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint stock_products_pkey primary key (id),
  constraint stock_products_product_category_id_fkey foreign KEY (product_category_id) references product_categories (id),
  constraint stock_products_product_measure_unit_id_fkey foreign KEY (product_measure_unit_id) references product_measure_units (id)
) TABLESPACE pg_default;

CREATE TABLE public.currency_types (
    id SERIAL PRIMARY KEY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    UNIQUE (abbreviation),
    created_at TIMESTAMP with time zone NOT NULL default now()
);

CREATE TABLE public.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

CREATE TABLE public.countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_user_genders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    abbreviation VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (abbreviation),
    CONSTRAINT platform_user_genders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_settings (
    id BIGINT generated by default AS identity,
    contact_number VARCHAR(15) NULL,
    developer_name VARCHAR(100) NOT NULL,
    developer_contact_email VARCHAR(100) NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    CONSTRAINT platform_settings_pkey PRIMARY KEY (id),
    CONSTRAINT platform_settings_name_key UNIQUE (developer_name)
) TABLESPACE pg_default;

CREATE TABLE public.platform_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_user_role_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platform_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NULL,
    last_name TEXT NULL,
    phone TEXT NULL,
    email TEXT NULL,
    username TEXT NULL,
    password TEXT NULL,
    is_root BOOLEAN NULL default false,
    user_role_id BIGINT NULL,
    created_at TIMESTAMP with time zone NOT NULL default now(),
    is_active BOOLEAN NULL default false,
    is_banned BOOLEAN NULL default false,
    is_blocked BOOLEAN NULL default false,
    token TEXT NULL,
    dni_ssn TEXT NULL,
    platform_user_gender_id BIGINT NULL default '4'::BIGINT,
    country_id BIGINT NULL,
    birthdate DATE NULL,
    CONSTRAINT platform_users_pkey PRIMARY KEY (id),
    CONSTRAINT platform_users_email_key unique (email),
    CONSTRAINT platform_users_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_platform_user_gender_id_fkey FOREIGN KEY (platform_user_gender_id) REFERENCES platform_user_genders (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT platform_users_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES platform_user_roles (id) ON UPDATE CASCADE ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE TABLE public.platform_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT platform_states_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sale_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sale_total DECIMAL(10,2) NOT NULL,
    is_closed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sales_user FOREIGN KEY (user_id) 
        REFERENCES platform_users(id) ON DELETE RESTRICT ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    stock_product_id BIGINT NOT NULL,
    quantity INT DEFAULT 1,
    sale_item_total DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sale_item_product FOREIGN KEY (stock_product_id) 
        REFERENCES stock_products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) 
        REFERENCES sales(id) ON DELETE CASCADE ON UPDATE CASCADE
) TABLESPACE pg_default;

